<robot name="wheel" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="base_length" value="0.8"/>
    <xacro:property name="base_wide" value="0.4"/>
    <xacro:property name="base_high" value="0.2"/>
    <xacro:property name="base_to_ground" value="0.08"/>

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_wide" value="0.05"/>
    <xacro:property name="wheel_m" value="0.2"/>

    <xacro:property name="mechanical_reduction" value="50"/>

    <xacro:macro name="wheel" params="wheel_name flag_x flag_y">

        <xacro:property name="PI" value="3.14159"/>

        <link name="${wheel_name}_wheel">
            <inertial>
                <mass value="${wheel_m}"/>
                <inertia ixx="${1/12 * wheel_m * (3 * wheel_radius * wheel_radius + wheel_wide * wheel_wide)}"
                         ixy="0" ixz="0"
                         iyy="${1/12 * wheel_m * (3 * wheel_radius * wheel_radius + wheel_wide * wheel_wide)}"
                         iyz="0" izz="${1/2 * wheel_m * wheel_radius * wheel_radius}"
                />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
                </geometry>
                <material name="color_wheel">
                    <color rgba="0.780 0.082 0.522 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
                </geometry>
            </collision>
        </link>

        <joint name="base_link2${wheel_name}_wheel" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <origin xyz="${flag_x * base_length / 4} ${flag_y * (wheel_wide + base_wide / 2)}
            ${wheel_radius - base_to_ground - base_high / 2}"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>


    <xacro:macro name="wheel_transmission" params="wheel_name">

        <transmission name="${wheel_name}_wheel_tran">
            <!--指定传动类型-->
            <type>transmission_interface/SimpleTransmission</type>
            <!--传动系统所代表的关节-->
            <actuator name="${wheel_name}_wheel_motor">
                <!--可选，指定硬件接口-->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <!--可选，指定关节制动器之间机械减速比，并非所有传动系统都需要此标签-->
                <mechanicalReduction>${mechanical_reduction}</mechanicalReduction>
            </actuator>

            <joint name="base_link2${wheel_name}_wheel">
                <!--指定硬件接口，注意，当在Gazebo中加载此传动系统是，值应为EffortJointInterface-->
                <!--而在RobotHW中加载此传动系统时，值应为hardware_interface/EffortJointInterface-->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>


</robot>